In [18]:
import numpy as np

weather_data = {
    "city": [
        "Kathmandu", "Pokhara", "Delhi", "Tokyo", "London",
        "New York", "Sydney", "Dubai"
    ],
    
    "date": [
        "2026-03-09", "2026-03-09", "2026-03-09", "2026-03-09",
        "2026-03-09", "2026-03-09", "2026-03-09", "2026-03-09"
    ],
    
    "temperature_c": [
        18, 20, np.nan, 16, 12, 10, 22, np.nan
    ],
    
    "humidity_percent": [
        60, np.nan, 50, 55, 70, "Not Available", 58, 40
    ],
    
    "wind_speed_kmh": [
        10, 8, 12, np.nan, 20, 18, "Not Available", 9
    ],
    
    "weather_condition": [
        "Cloudy", "Rainy", "Sunny", np.nan,
        "Foggy", "Snowy", "Sunny", "Hot"
    ]
}

In [19]:

df = pd.DataFrame(weather_data)
df

,city,date,temperature_c,humidity_percent,wind_speed_kmh,weather_condition
0,Kathmandu,2026-03-09,18.0,60,10,Cloudy
1,Pokhara,2026-03-09,20.0,NaN,8,Rainy
2,Delhi,2026-03-09,NaN,50,12,Sunny
3,Tokyo,2026-03-09,16.0,55,NaN,NaN
4,London,2026-03-09,12.0,70,20,Foggy
5,New York,2026-03-09,10.0,Not Available,18,Snowy
6,Sydney,2026-03-09,22.0,58,Not Available,Sunny
7,Dubai,2026-03-09,NaN,40,9,Hot

In [20]:

df.set_index("city")
df

,city,date,temperature_c,humidity_percent,wind_speed_kmh,weather_condition
0,Kathmandu,2026-03-09,18.0,60,10,Cloudy
1,Pokhara,2026-03-09,20.0,NaN,8,Rainy
2,Delhi,2026-03-09,NaN,50,12,Sunny
3,Tokyo,2026-03-09,16.0,55,NaN,NaN
4,London,2026-03-09,12.0,70,20,Foggy
5,New York,2026-03-09,10.0,Not Available,18,Snowy
6,Sydney,2026-03-09,22.0,58,Not Available,Sunny
7,Dubai,2026-03-09,NaN,40,9,Hot