In [9]:
import pandas as pd 
import numpy as np


weather_data = {
    "city": [
        "Kathmandu", "Pokhara", "Delhi", "Tokyo", "London",
        "New York", "Sydney", "Dubai"
    ],
    
    "date": [
        "2026-03-01",
        "2026-03-02",
        "2026-03-04",   # 03 missing
        "2026-03-05",
        "2026-03-07",   # 06 missing
        "2026-03-08",
        "2026-03-10",   # 09 missing
        "2026-03-12"    # 11 missing
    ],
    
    "temperature_c": [
        18, 20, np.nan, 16, 12, 10, 22, np.nan
    ],
    
    "humidity_percent": [
        60, np.nan, 50, 55, 70, "Not Available", 58, 40
    ],
    
    "wind_speed_kmh": [
        10, 8, 12, np.nan, 20, 18, "Not Available", 9
    ],
    
    "weather_condition": [
        "Cloudy", "Rainy", "Sunny", np.nan,
        "Foggy", "Snowy", "Sunny", "Hot"
    ]
}

In [23]:
df  = pd.DataFrame(weather_data)
df["date"] = pd.to_datetime(df["date"])
df.replace("Not Available", np.nan, inplace=True)
df.set_index("date", inplace=True)
df

C:\Users\VICTUS\AppData\Local\Temp\ipykernel_1776\4235852793.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("Not Available", np.nan, inplace=True)

,city,temperature_c,humidity_percent,wind_speed_kmh,weather_condition
date,,,,,
2026-03-01,Kathmandu,18.0,60.0,10.0,Cloudy
2026-03-02,Pokhara,20.0,NaN,8.0,Rainy
2026-03-04,Delhi,NaN,50.0,12.0,Sunny
2026-03-05,Tokyo,16.0,55.0,NaN,NaN
2026-03-07,London,12.0,70.0,20.0,Foggy
2026-03-08,New York,10.0,NaN,18.0,Snowy
2026-03-10,Sydney,22.0,58.0,NaN,Sunny
2026-03-12,Dubai,NaN,40.0,9.0,Hot

In [32]:
# new_df = df.fillna({
#     "city ": "Unknown",
#     "temperature_c": df["temperature_c"].mean(),
#     "humidity_percent": df["humidity_percent"].mean(),
#     "wind_speed_kmh": df["wind_speed_kmh"].mean(),
#     "weather_condition": "Unknown"
# })
# new_df   (this type of method can also be used to fill the null values with mean, median or mode of the column)

new_df = df.interpolate(method="time")
# new_df = df.fillna({
#     "city ": "Unknown",
#     "weather_condition": "Unknown"
# })
new_df

C:\Users\VICTUS\AppData\Local\Temp\ipykernel_1776\160100054.py:10: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  new_df = df.interpolate(method="time")

,city,temperature_c,humidity_percent,wind_speed_kmh,weather_condition
date,,,,,
2026-03-01,Kathmandu,18.000000,60.000000,10.000000,Cloudy
2026-03-02,Pokhara,20.000000,56.666667,8.000000,Rainy
2026-03-04,Delhi,17.333333,50.000000,12.000000,Sunny
2026-03-05,Tokyo,16.000000,55.000000,14.666667,NaN
2026-03-07,London,12.000000,70.000000,20.000000,Foggy
2026-03-08,New York,10.000000,66.000000,18.000000,Snowy
2026-03-10,Sydney,22.000000,58.000000,13.500000,Sunny
2026-03-12,Dubai,22.000000,40.000000,9.000000,Hot

In [41]:
dt = pd.date_range(start = "2026-03-01", end = "2026-03-12" , freq="D")
idx = pd.DatetimeIndex(dt)
df = df.reindex(idx)
df


## now after this we can apply the interpolation method to fill the null values in the date column as well as other columns

,city,temperature_c,humidity_percent,wind_speed_kmh,weather_condition
2026-03-01,Kathmandu,18.0,60.0,10.0,Cloudy
2026-03-02,Pokhara,20.0,NaN,8.0,Rainy
2026-03-03,NaN,NaN,NaN,NaN,NaN
2026-03-04,Delhi,NaN,50.0,12.0,Sunny
2026-03-05,Tokyo,16.0,55.0,NaN,NaN
2026-03-06,NaN,NaN,NaN,NaN,NaN
2026-03-07,London,12.0,70.0,20.0,Foggy
2026-03-08,New York,10.0,NaN,18.0,Snowy
2026-03-09,NaN,NaN,NaN,NaN,NaN
2026-03-10,Sydney,22.0,58.0,NaN,Sunny
2026-03-11,NaN,NaN,NaN,NaN,NaN
2026-03-12,Dubai,NaN,40.0,9.0,Hot

In [43]:
new_df = df.fillna({
    "temperature_c": df["temperature_c"].mean(),
    "humidity_percent": df["humidity_percent"].interpolate()[0],
    "wind_speed_kmh": df["wind_speed_kmh"].median(),
    "weather_condition": "Unknown"
})
new_df

C:\Users\VICTUS\AppData\Local\Temp\ipykernel_1776\3371214659.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  "humidity_percent": df["humidity_percent"].interpolate()[0],

,city,temperature_c,humidity_percent,wind_speed_kmh,weather_condition
2026-03-01,Kathmandu,18.000000,60.0,10.0,Cloudy
2026-03-02,Pokhara,20.000000,60.0,8.0,Rainy
2026-03-03,NaN,16.333333,60.0,11.0,Unknown
2026-03-04,Delhi,16.333333,50.0,12.0,Sunny
2026-03-05,Tokyo,16.000000,55.0,11.0,Unknown
2026-03-06,NaN,16.333333,60.0,11.0,Unknown
2026-03-07,London,12.000000,70.0,20.0,Foggy
2026-03-08,New York,10.000000,60.0,18.0,Snowy
2026-03-09,NaN,16.333333,60.0,11.0,Unknown
2026-03-10,Sydney,22.000000,58.0,11.0,Sunny
2026-03-11,NaN,16.333333,60.0,11.0,Unknown
2026-03-12,Dubai,16.333333,40.0,9.0,Hot